sudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install:
    - travis_retry pip install coverage pytest requests-oauthlib pytz mock
script:
    - coverage run -m py.test -s
    - coverage report
